[package]
name = "reth-eth-wire"
description = "Implements the eth/64 and eth/65 P2P protocols"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"

[dependencies]
bytes = { version = "1.1" }
hex = "0.4"
thiserror = "1"
serde = "1"

# reth
reth-primitives = { path = "../../primitives" }
reth-rlp = { path = "../../common/rlp", features = ["alloc", "derive", "std", "ethereum-types", "smol_str"] }

# used for Chain and builders
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }

tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3.24"
tokio-stream = "0.1.11"
pin-project = "1.0"
tracing = "0.1.37"
snap = "1.0.5"
smol_str = { version = "0.1", features = ["serde"] }
metrics = "0.20.1"

[dev-dependencies]
reth-ecies = { path = "../ecies" }
reth-tracing = { path = "../../tracing" }
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }

test-fuzz = "3.0.4"
tokio-util = { version = "0.7.4", features = ["io", "codec"] }
hex-literal = "0.3"
rand = "0.8"
secp256k1 = { version = "0.24.2", features = ["global-context", "rand-std", "recovery"] }
